# Project Identification
sonar.projectKey=secure-notes-app
sonar.projectName=Secure Notes App
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://localhost:9000
sonar.token=squ_2a5fb1e5fe8db493d88c9488283e7abc94c70543

# Source Code
sonar.sources=.

# Exclude unnecessary folders
sonar.exclusions=node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8